version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: docker
       MYSQL_DATABASE: docker
       MYSQL_USER: docker
       MYSQL_PASSWORD: docker

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./themes:/var/www/html/wp-content/themes
     ports:
       - "8888:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: docker
       WORDPRESS_DB_PASSWORD: docker
volumes:
    db_data:
